version: '3.7'

services:
    youtube_dl_api_dev:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - '8080:8080'
        restart: always
        command: tail -F anything